#cloud-config
repo_update: true
repo_upgrade: all

packages:

- curl
- git
- screen
- nfs-utils
- amazon-efs-utils
- jq
- nmap-ncat

write_files:

- encoding: b64
  content: ${b64_env_cloud_prefix}
  owner: root:root
  path: ${path_env_cloud_prefix}
  permissions: '0644'

runcmd:

- echo "init finished ..."
